### ISSUE TITLE
Problem with async await

### ISSUE THREAD

**Issue by Seinh** [LiquidLabsGmbH/redux-direct#1]
There is a problem with chained actions using async await:

```
const actions = createActions('actions', {
  doSomething() {

    return { payload: true);
  },

 doAnotherThing() {

    return { other: true);
  },

  doSomethingAndAnotherThing() {

    return async (dispatch) => {
     console.log('HERE');
      await dispatch(this.doSomething());
      await dispatch(this.doSomethingAndAnotherThing());
    };
  },
});

```

In this example the internal async function of doSomethingAndAnotherThing is never executed

**Comment by fgnass** [comment]
In order for this to work a middleware needs to be installed that handles `{ payload: <function> }` shaped actions – `redux-thunk` doesn't do that but https://www.npmjs.com/package/redux-fsa-thunk for example does.
